# Generated by Django 3.0.7 on 2020-06-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categor_name',
            new_name='category_name',
        ),
    ]
